config/routes.rb
Rails.application.routes.draw do
  # get 'doses/new'

  # get 'doses/create'

  # get 'doses/destroy'

  # get 'cocktails/index'

  # get 'cocktails/show'

  # get 'cocktails/new'

  # get 'cocktails/create'

  root to: 'cocktails#index'



resources :cocktails, only: [:index, :new, :create, :show] do
  resources :doses, only: [:new, :create]
end
resources :doses, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true

end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, presence: true, uniqueness: { scope: :ingredient }
  validates :ingredient, presence: true, uniqueness: { scope: :cocktail }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

  has_many :doses
  has_many :cocktail, through: :doses

  validates :name, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  #before_action :find_cocktail, only: [:new, :create]

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @ingredients = Ingredient.all
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @ingredients = Ingredient.all
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
    <%= f.input :name, placeholder: "Mojito" %>
    <%= f.button :submit, class: "btn btn-primary"  %>
<% end %>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('http://www.vestocasa.it/wp-content/uploads/2017/05/bicchieri-cocktail-copertina-1.jpg');">
  <div class="banner-content">
    <h1>BartenderApp</h1>
    <p>Create your cocktail list</p>
    <a class="btn btn-primary btn-lg">Let's Start</a>
  </div>
</div>


<div class="container">
  <div class="row">
    <h1>Cocktails</h1>
    <div class="cards">

    <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-4">

        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');">

          <div class="card-category">Drink</div>

          <div class="card-description">
            <h2> <%= link_to cocktail.name, cocktail_path(cocktail) %></h2>
          </div>

          <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
          <a class="card-link" href="#" ></a>

        </div>
      </div>

      <% end %>

    </div>
  </div>
</div>


<%= link_to "Add a new cocktail", new_cocktail_path, class: "btn btn-primary" %>
</div>
</div>
</div>

app/views/cocktails/new.html.erb
<h2>Add Cocktails</h2>

<%= simple_form_for @cocktail do |f| %>
<%= f.input :name %>
<%= f.button :submit %>

<% end %>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1><%= @cocktail.name %></h1>
      <ul>
        <% @cocktail.doses.each do |dose| %>
        <li>
          <strong>
            <%= dose.description %>
            <%= dose.ingredient.name %>
          </strong>
        </li>
        <% end %>
        <ul>
           <%= link_to "All Cocktails", cocktails_path, class: "btn btn-primary" %>
           <%= link_to "Add a new ingredient", new_cocktail_dose_path(@cocktail), class: "btn btn-primary" %>
        </ul>

      </ul>
    </div>
  </div>
</div>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<h2>Add your doses and ingredients for <%= @cocktail.name %> </h2>

<%= simple_form_for [@cocktail, @dose] do |f| %>

<%= f.input :description %>
<%= f.association :ingredient, collection: @ingredients %>
<%= f.button :submit %>

<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This app is for real Barman
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
   <%= image_tag "logo.png" %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <a href="" class="navbar-wagon-item navbar-wagon-link">Bakeca</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Libraries</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Messages</a>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Bakeca</a></li>
        <li><a href="#">Libraries</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMisterCocktail</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

</head>

<body>
  <%= render 'layouts/navbar' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>